### ISSUE TITLE
torch.nn.modules.module.ModuleAttributeError: 'Graph2Tree' object has no attribute 'in_pad_token'

### ISSUE THREAD

**Issue by liamjxu** [LYH-YF/MWPToolkit#18]
Code version: [8779d0d](https://github.com/LYH-YF/MWPToolkit/commit/8779d0dbb00b4e4a4f861cc3f219f618bd94742f)
Command line (generated by https://mwptoolkit.readthedocs.io/en/latest/_static/cmd.html):
```bash
python run_mwptoolkit.py --model=Graph2Tree --dataset=asdiv-a --task_type=single_equation --gpu_id=0 --equation_fix=prefix
```
Error Message:
```
Traceback (most recent call last):
  File "run_mwptoolkit.py", line 26, in <module>
    run_toolkit(args.model, args.dataset, args.task_type, config_dict)
  File "/data/MWPToolkit/mwptoolkit/quick_start.py", line 215, in run_toolkit
    train_with_train_valid_test_split(config)
  File "/data/MWPToolkit/mwptoolkit/quick_start.py", line 103, in train_with_train_valid_test_split
    trainer.fit()
  File "/data/MWPToolkit/mwptoolkit/trainer/supervised_trainer.py", line 532, in fit
    loss_total, train_time_cost = self._train_epoch()
  File "/data/MWPToolkit/mwptoolkit/trainer/supervised_trainer.py", line 515, in _train_epoch
    batch_loss = self._train_batch(batch)
  File "/data/MWPToolkit/mwptoolkit/trainer/supervised_trainer.py", line 476, in _train_batch
    batch_loss = self.model.calculate_loss(batch)
  File "/data/MWPToolkit/mwptoolkit/model/Graph2Tree/graph2tree.py", line 161, in calculate_loss
    group_nums, target, output_all_layers=True)
  File "/data/MWPToolkit/mwptoolkit/model/Graph2Tree/graph2tree.py", line 105, in forward
    seq_mask = torch.eq(seq, self.in_pad_token).to(self.device)
  File "/data/anaconda3/envs/number/lib/python3.7/site-packages/torch/nn/modules/module.py", line 779, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'Graph2Tree' object has no attribute 'in_pad_token'
```

**Comment by LYH-YF** [comment]
it seems an error in v0.0.6, sorry about that.

**Comment by liamjxu** [comment]
Thanks for the prompt resolution!
